---
- hosts: servers
  tasks:
  - name: Set-up git
    yum:
      name: git
      state: latest
    become: true
  - name: transfer Jenkins install
    copy: src=install_jenkins.sh dest=/home/ansible/
 
  - name: Jenkins install
    command: sh /home/ansible/install_jenkins.sh
    become: true
...
